const sampleItems = [
  {
    id: 1,
    name: 'Susu UHT 1L',
    category: 'bahan_baku',
    qty: 12,
    unit: 'pcs',
    price: 18000,
    total: 216000,
    addsStock: true,
    ingredientId: 2,
    stockQty: 12,
    stockUnit: 'pcs',
  },
  {
    id: 2,
    name: 'Gula Aren 1L',
    category: 'bahan_baku',
    qty: 2,
    unit: 'botol',
    price: 25000,
    total: 50000,
    addsStock: true,
    ingredientId: 3,
    stockQty: 2000,
    stockUnit: 'ml',
  },
  {
    id: 3,
    name: 'Cup 16oz',
    category: 'packaging',
    qty: 100,
    unit: 'pcs',
    price: 750,
    total: 75000,
    addsStock: true,
    ingredientId: 6,
    stockQty: 100,
    stockUnit: 'pcs',
  },
  {
    id: 4,
    name: 'Sedotan',
    category: 'packaging',
    qty: 100,
    unit: 'pcs',
    price: 150,
    total: 15000,
    addsStock: true,
    ingredientId: 8,
    stockQty: 100,
    stockUnit: 'pcs',
  },
];

export async function scanReceipt({ file }) {
  return {
    merchantName: 'Supplier Malinau',
    transactionDate: new Date().toISOString(),
    confidence: 0.92,
    originalFileName: file?.originalname || 'foto-resi.jpg',
    fileSize: file?.size || null,
    items: sampleItems.map((item) => ({ ...item })),
  };
}
