import fs from 'fs';

const db = JSON.parse(fs.readFileSync('scratch/vps-db-clone.json', 'utf8'));

// We want to reconstruct the chronological sequence of events.
// For events on the same day:
// 1. Sales and Expenses happen during the day.
// 2. Transfers/adjustments happen.
// 3. Tutup Kas happens at the end of the day.

// Let's gather all events:
const events = [];

db.sales.forEach(sale => {
  if (sale.paymentMethod === 'cash') {
    events.push({
      date: sale.date,
      type: 'sale',
      amount: sale.total,
      description: `Sales: ${sale.items?.map(i => `${i.name} ${i.qty}x`).join(', ')}`
    });
  }
});

db.expenses.forEach(exp => {
  if (exp.cashAccountId === 'kas-utama' && exp.status !== 'rejected') {
    events.push({
      date: exp.date,
      type: 'expense',
      amount: -exp.total,
      description: `Expense: ${exp.description}`
    });
  }
});

db.cashTransactions.forEach(tx => {
  // Ignore transactions generated by sales, expenses or close cash, as we want to handle the close cash action and sales/expenses explicitly.
  // Wait, what transactions are manual?
  // Let's check:
  // - sourceId/sourceType = 'sale' -> generated by sale
  // - sourceType = 'expense' -> generated by expense
  // - category = 'koreksi' & description starts with 'Koreksi selisih tutup kas' -> generated by close cash
  
  const isGenerated = (tx.sourceType === 'sale' || tx.sourceType === 'expense' || (tx.category === 'koreksi' && tx.description.includes('Koreksi selisih tutup kas')));
  
  if (!isGenerated) {
    if (tx.type === 'transfer') {
      if (tx.fromAccountId === 'kas-utama') {
        events.push({
          date: tx.date,
          type: 'transfer_out',
          amount: -tx.amount,
          description: `Transfer Out to ${tx.toAccountId}: ${tx.description}`
        });
      }
      if (tx.toAccountId === 'kas-utama') {
        events.push({
          date: tx.date,
          type: 'transfer_in',
          amount: tx.amount,
          description: `Transfer In from ${tx.fromAccountId}: ${tx.description}`
        });
      }
    } else if (tx.type === 'koreksi' && tx.accountId === 'kas-utama') {
      // Manual adjustment
      // Wait, is it positive or negative? In analyze_ledger we saw tx with Type: koreksi, Category: koreksi, Description: bonus, amount: 42000
      // Let's see if adjustment is positive or negative. Let's find direction.
      const amount = tx.amount;
      events.push({
        date: tx.date,
        type: 'correction',
        amount: amount, // assume positive for now, let's verify if there is any direction
        description: `Manual Correction: ${tx.description}`
      });
    }
  }
});

// Sort events by date ASC
events.sort((a, b) => new Date(a.date) - new Date(b.date));

console.log('--- Chronological Events Flow (Without Close Cash overwrites) ---');
let runningBalance = 0;
events.forEach((ev, idx) => {
  runningBalance += ev.amount;
  console.log(`${idx + 1}. [${ev.date}] ${ev.type.toUpperCase()}: ${ev.description} | change: ${ev.amount} -> balance: ${runningBalance}`);
});

console.log('\nNow let\'s overlay the Close Cash actions.');
console.log('If the user closes each day in chronological order:');
// Let's group events by day, and apply close cash at the end of each day.
const days = ['2026-05-31', '2026-06-01', '2026-06-02', '2026-06-03'];

let balance = 0;
days.forEach(day => {
  console.log(`\n=== Day: ${day} ===`);
  const dayEvents = events.filter(ev => ev.date.startsWith(day));
  dayEvents.forEach(ev => {
    balance += ev.amount;
    console.log(`  Event: [${ev.date.substring(11, 19)}] ${ev.type.toUpperCase()} | ${ev.description} (${ev.amount}) -> balance: ${balance}`);
  });
  
  // Find close cash session for this day
  const session = db.cashSessions.find(s => s.date === day);
  if (session) {
    console.log(`  [CLOSE CASH] Expected: ${session.expectedCash}, Actual/Closing: ${session.closingCash}, Diff: ${session.difference}`);
    balance = session.closingCash; // Overwrite balance with actual closing cash
    console.log(`  --> Balance updated to Closing Cash: ${balance}`);
  } else {
    console.log(`  [CLOSE CASH] No session closed for this day.`);
  }
});

console.log('\nFinal Chronological Balance with Close Cash:', balance);
